<?php
/**
 * Site search enhancements.
 *
 * @package ETOS
 */

defined( 'ABSPATH' ) || exit;

/**
 * Extend the public WordPress search to ETOS ACF content fields.
 *
 * ACF stores the editable content used by ETOS pages and custom post types
 * in post meta. Native WordPress search does not search these values.
 *
 * Only public main search queries are affected and only meta keys beginning
 * with "etos_" are searched.
 *
 * @param string   $search Search SQL generated by WordPress.
 * @param WP_Query $query  Current query.
 *
 * @return string
 */
function etos_extend_search_to_acf_fields( $search, $query ) {
    if (
        is_admin()
        || ! $query->is_main_query()
        || ! $query->is_search()
    ) {
        return $search;
    }

    global $wpdb;

    $search_terms = isset( $query->query_vars['search_terms'] )
        ? (array) $query->query_vars['search_terms']
        : array();

    if ( empty( $search_terms ) ) {
        return $search;
    }

    $exact = ! empty( $query->query_vars['exact'] );
    $exclusion_prefix = apply_filters(
        'wp_query_search_exclusion_prefix',
        '-'
    );

    $meta_key_pattern = $wpdb->esc_like( 'etos_' ) . '%';
    $term_clauses = array();

    foreach ( $search_terms as $term ) {
        $exclude = (
            $exclusion_prefix
            && str_starts_with( $term, $exclusion_prefix )
        );

        if ( $exclude ) {
            $term = substr(
                $term,
                strlen( $exclusion_prefix )
            );
        }

        $term = trim( $term );

        if ( '' === $term ) {
            continue;
        }

        $like = $wpdb->esc_like( $term );

        if ( ! $exact ) {
            $like = '%' . $like . '%';
        }

        if ( $exclude ) {
            $term_clauses[] = $wpdb->prepare(
                "(
                    {$wpdb->posts}.post_title NOT LIKE %s
                    AND {$wpdb->posts}.post_excerpt NOT LIKE %s
                    AND {$wpdb->posts}.post_content NOT LIKE %s
                    AND NOT EXISTS (
                        SELECT 1
                        FROM {$wpdb->postmeta} AS etos_search_meta
                        WHERE etos_search_meta.post_id = {$wpdb->posts}.ID
                            AND etos_search_meta.meta_key LIKE %s
                            AND etos_search_meta.meta_value LIKE %s
                    )
                )",
                $like,
                $like,
                $like,
                $meta_key_pattern,
                $like
            );
        } else {
            $term_clauses[] = $wpdb->prepare(
                "(
                    {$wpdb->posts}.post_title LIKE %s
                    OR {$wpdb->posts}.post_excerpt LIKE %s
                    OR {$wpdb->posts}.post_content LIKE %s
                    OR EXISTS (
                        SELECT 1
                        FROM {$wpdb->postmeta} AS etos_search_meta
                        WHERE etos_search_meta.post_id = {$wpdb->posts}.ID
                            AND etos_search_meta.meta_key LIKE %s
                            AND etos_search_meta.meta_value LIKE %s
                    )
                )",
                $like,
                $like,
                $like,
                $meta_key_pattern,
                $like
            );
        }
    }

    if ( empty( $term_clauses ) ) {
        return $search;
    }

    $search = ' AND (' . implode( ' AND ', $term_clauses ) . ')';

    if ( ! is_user_logged_in() ) {
        $search .= " AND ({$wpdb->posts}.post_password = '')";
    }

    return $search;
}
add_filter(
    'posts_search',
    'etos_extend_search_to_acf_fields',
    10,
    2
);
/**
 * Get a useful excerpt for a search result.
 *
 * Prefers ETOS ACF content that matches the current search phrase.
 *
 * @param int $post_id    Post ID.
 * @param int $word_limit Maximum excerpt length in words.
 *
 * @return string
 */
function etos_get_search_result_excerpt( $post_id, $word_limit = 24 ) {
    $post_id = (int) $post_id;

    if ( $post_id <= 0 ) {
        return '';
    }

    $excerpt = trim(
        (string) get_post_field(
            'post_excerpt',
            $post_id
        )
    );

    if ( '' !== $excerpt ) {
        return wp_trim_words(
            wp_strip_all_tags(
                strip_shortcodes( $excerpt )
            ),
            $word_limit,
            '…'
        );
    }

    $search_terms = get_query_var( 'search_terms' );

    if ( ! is_array( $search_terms ) ) {
        $search_terms = array();
    }

    $search_terms = array_values(
        array_filter(
            array_map(
                'trim',
                $search_terms
            )
        )
    );

    $all_meta = get_post_meta( $post_id );
    $candidates = array();

    foreach ( $all_meta as $meta_key => $values ) {
        if ( ! str_starts_with( $meta_key, 'etos_' ) ) {
            continue;
        }

        foreach ( (array) $values as $value ) {
            if (
                ! is_string( $value )
                || '' === trim( $value )
                || is_serialized( $value )
            ) {
                continue;
            }

            $text = trim(
                wp_strip_all_tags(
                    strip_shortcodes( $value )
                )
            );

            if ( '' === $text ) {
                continue;
            }

            $matches = 0;

            foreach ( $search_terms as $term ) {
                if ( false !== mb_stripos( $text, $term ) ) {
                    ++$matches;
                }
            }

            if ( 0 === $matches ) {
                continue;
            }

            $priority = 6;

            if ( str_ends_with( $meta_key, '_text' ) ) {
                $priority = 1;
            } elseif ( str_ends_with( $meta_key, '_lead' ) ) {
                $priority = 2;
            } elseif ( str_ends_with( $meta_key, '_intro' ) ) {
                $priority = 3;
            } elseif ( str_ends_with( $meta_key, '_description' ) ) {
                $priority = 4;
            } elseif ( str_ends_with( $meta_key, '_title' ) ) {
                $priority = 5;
            }

            $candidates[] = array(
                'text'     => $text,
                'matches'  => $matches,
                'priority' => $priority,
            );
        }
    }

    if ( ! empty( $candidates ) ) {
        usort(
            $candidates,
            static function ( $a, $b ) {
                if ( $a['matches'] !== $b['matches'] ) {
                    return $b['matches'] <=> $a['matches'];
                }

                if ( $a['priority'] !== $b['priority'] ) {
                    return $a['priority'] <=> $b['priority'];
                }

                return strlen( $b['text'] ) <=> strlen( $a['text'] );
            }
        );

        return wp_trim_words(
            $candidates[0]['text'],
            $word_limit,
            '…'
        );
    }

    $content = trim(
        (string) get_post_field(
            'post_content',
            $post_id
        )
    );

    if ( '' === $content ) {
        return '';
    }

    return wp_trim_words(
        wp_strip_all_tags(
            strip_shortcodes( $content )
        ),
        $word_limit,
        '…'
    );
}